### ISSUE TITLE
How to create a badge for repositories inside an organization?

### ISSUE THREAD

**Issue by samacker77** [hehuapei/visitor-badge#1]

**Comment by hehuapei** [comment]
All you have to do is to add below markdown markup to your markdown content:
```
 ![visitors](https://visitor-badge.laobi.icu/badge?page_id=page.id)
```
                   
recommend you to follow page_id rules below:

For README.md file, use ${organization.name}.${organization.repo.id}, https://visitor-badge.laobi.icu/badge?page_id=hehuapei.visitor-badge for example.

**Comment by hehuapei** [comment]
No more replies, temporarily closed!
