### ISSUE TITLE
The number of visitors does not change

### ISSUE THREAD

**Issue by yasserbdj96** [hehuapei/visitor-badge#10]
I use the visitors button in all my projects, for a while it has been working normally, but in the past few days the number of visitors has not changed in all my projects, even on my personal page...

The number of visitors does not change even if I renew the page myself or from other browsers

An example of one of the buttons I used:

The number is fixed in : 6761

[![Visitors](https://visitor-badge.laobi.icu/badge?page_id=yasserbdj96.hiphp)](https://github.com/yasserbdj96/hiphp)

**Comment by hehuapei** [comment]
Thank you for the remind! I'm sorry about my misstake! Now i fixed it.

**Comment by yasserbdj96** [comment]
Yes it has been fixed and thanks for the button.
