### ISSUE TITLE
Not Working Anymore

### ISSUE THREAD

**Issue by Ddhruv-IOT** [hehuapei/visitor-badge#14]
Since yesterday it's not working, anyone please suggest some alternative

![Screenshot 2023-01-03 142945](https://user-images.githubusercontent.com/54676859/210326386-95d651fd-d54e-4a00-a06a-be490d485b1b.jpg)

![Screenshot 2023-01-03 143021](https://user-images.githubusercontent.com/54676859/210326549-2c013f83-d16c-462d-9706-828c2ec0e555.jpg)

**Comment by hehuapei** [comment]
Insufficient machine resources lead to the offline of service. I have cleaned up and restarted the service!

**Comment by Ddhruv-IOT** [comment]
Okay, got it. Thanks for reply.
