### ISSUE TITLE
Error: Count API Failed

### ISSUE THREAD

**Issue by LeGeRyChEeSe** [hehuapei/visitor-badge#19]
![Screenshot_2023-05-04-00-46-42-388-edit_com.android.chrome.jpg](https://user-images.githubusercontent.com/64637517/236067780-28dee068-91c4-4cf0-9f8e-0ca07762de67.jpg)

As shown in the pic below, i can't get the number of visitors of my github repo. Type "lanplaypy" on github to find the repo if you want to check. It's the same for my other repo named "EVApy" but it's working for my other repo named "Eva_bot" so i don't understand where the error comes from.

Could you check please ?

Br.

**Comment by hehuapei** [comment]
Thank you for this feedback! 
I got it when I used the new page_id. I have fixed and it's working now!

**Comment by hehuapei** [comment]
Thank you for this feedback!
I got it when I used the new page_id. I have fixed and it's working now!

**Comment by LeGeRyChEeSe** [comment]
Thank you it's working !
