### ISSUE TITLE
CountAPI key for the original instance results in a different count

### ISSUE THREAD

**Issue by Nathan13888** [hehuapei/visitor-badge#2]
Although .env file uses `guess_what`, it seems that a different key is actually used instead.

Fyi, I've been using this alternate server for over the past 6 months.

**Example**:
`https://visitor-badge.glitch.me/badge?page_id=nathan13888.visiter.badge` --> ~300

`https://visitor-badge.laobi.icu/badge?page_id=nathan13888.visiter.badge` --> ~1900

**Comment by hehuapei** [comment]
My count-API uses my local service, so it will be out of sync with the public count-API's results.

**Comment by Nathan13888** [comment]
Hi @hehuapei,

Some time ago, I made a Visitor Badge replacement using Golang that was theoretically faster and had more features. Here's my project: https://github.com/Nathan13888/VisitorBadgeReloaded

I'm planning to continue development soon in the future. Some of my plans are already written in the README.

One of the more important things I wanted to implement was a "cache" using some sort of KV database (such as Redis) to potentially improve speed.

If you would like to help with this, that would be greatly appreciated :smile: 

Is there is anything you would like to know, please create an Issue on my project. Thanks.
