### ISSUE TITLE
Error count api failed

### ISSUE THREAD

**Issue by conp7** [hehuapei/visitor-badge#21]
您好，我这边显示Error count api failed
请问怎么解决
期待您的回信
我的邮箱：756246423@qq.com

**Comment by hehuapei** [comment]
后端服务掉线了, 已经重新启动了!

**Comment by conp7** [comment]
thank you！！！



发自我的iPhone


------------------ Original ------------------
From: wiken ***@***.***&gt;
Date: Mon,Sep 18,2023 1:55 PM
To: hehuapei/visitor-badge ***@***.***&gt;
Cc: conp ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [hehuapei/visitor-badge] Error count api failed (Issue #21)





 
后端服务掉线了, 已经重新启动了!

**Comment by conp7** [comment]
您好 我忘记了我的代码 我的网站是id66.xyz 麻烦帮我发一下浏览数量



发自我的iPhone


------------------ Original ------------------
From: wiken ***@***.***&gt;
Date: Mon,Sep 18,2023 1:55 PM
To: 756246423 ***@***.***&gt;
Subject: Re: [hehuapei/visitor-badge] Error count api failed (Issue #21)





 
后端服务掉线了, 已经重新启动了!

**Comment by hehuapei** [comment]
> 您好 我忘记了我的代码 我的网站是id66.xyz 麻烦帮我发一下浏览数量 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: wiken ***@***.***&gt; Date: Mon,Sep 18,2023 1:55 PM To: 756246423 ***@***.***&gt; Subject: Re: [hehuapei/visitor-badge] Error count api failed (Issue #21) 后端服务掉线了, 已经重新启动了! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

不知道代码没办法查的, 浏览量都是根据代码查出来的
