### ISSUE TITLE
Select the unit of count when displayed

### ISSUE THREAD

**Issue by sheepzh** [hehuapei/visitor-badge#4]
![](https://img.shields.io/badge/visitors-10100-blue)
=>
![](https://img.shields.io/badge/visitors-10K+-blue)

**Comment by DevCleverton** [comment]
I find it interesting, especially if there was something like a more intuitive counter!

**Comment by hehuapei** [comment]
@sheepzh @DevCleverton  Now,  you can show it by parameter: format!

#### Usage
```markdown
![visitor badge](https://visitor-badge.laobi.icu/badge?page_id=example&format=true)
```
![visitor badge](https://visitor-badge.laobi.icu/badge?page_id=jwenjian.visitor-badge&format=true)
