### ISSUE TITLE
Only query the counter state without updating it

### ISSUE THREAD

**Issue by FabianBartl** [hehuapei/visitor-badge#7]
I would like it if there was the possibility to query only the counter value without always incrementing it directly:

For this there could be for example an URL parameter `update` which would be `true` by default. But if this parameter is `false`, then only the counter value will be queried without incrementing the counter.

**Comment by hehuapei** [comment]
Thanks for the suggestion! I have implemented this feature, you can use by parameter: query_only!

#### Usage
```markdown
![visitor badge](https://visitor-badge.laobi.icu/badge?page_id=example&query_only=true)
```
![visitor badge](https://visitor-badge.laobi.icu/badge?page_id=example&query_only=true)
