### ISSUE TITLE
Count increase of visitor even if the owner/user check or refresh the page.

### ISSUE THREAD

**Issue by SKsaikiran** [hehuapei/visitor-badge#8]
I am using the visitor badge from two months , **as noticed whenever i refresh the overview page the visitor count increases** . So as the problem is the user/owner of the account who used visitor badge in there overview can increases their visitor count as it is not the correct value .

**Comment by hehuapei** [comment]
You are right, the number increase when every page loaded, it can't judge the increase based on the account!
